### ISSUE TITLE
 Altimeter calibration test

### ISSUE THREAD

**Issue by tulku** [tulku/test#20]
# Altimeter calibration test

This test should be done on a robot with a working barometer. Currently only our Relay 1.5 robot has one.

Now that we have freshly installed robots they don't have the altimeter calibrated. The calibration should be done a computer with the testing software installed (check instructions in the Simulation test).

<details><summary>Instructions</summary>
<p>

1. Download the [elevator bagfile](https://s3.amazonaws.com/uploads.hipchat.com/67924/3875671/pYmn1zLjj6lTY6J/savihq_elevator_ride_recording.bag.bz2).
1. Download the matching [elevator logs].(https://s3.amazonaws.com/uploads.hipchat.com/67924/3875671/f5bwv3KQRQHCXrv/savihq_splunk_logs.csv).
1. Follow the instructions [in this wiki](https://github.com/savioke/relay-ros/wiki/Floor-exclusion#configuration).
1. Upload the calibrated file to `savioke_config`, similar to [this pr](https://github.com/savioke/savioke-config/pull/310).
1. Restart the robot software and make sure that the calibrated model was downloaded.
1. Verify that the published floor estimate is correct.

Use this as initial building information file:

```yaml
floor_estimation_model:
  site_shortname: savihq
  ref_floor_name: '7'
  floors:
    - {allow_navigation: true, floor_name: 'G'}
    - {allow_navigation: true, floor_name: 'P'}
    - {allow_navigation: true, floor_name: '2'}
    - {allow_navigation: true, floor_name: '3'}
    - {allow_navigation: true, floor_name: '4'}
    - {allow_navigation: true, floor_name: '5'}
    - {allow_navigation: true, floor_name: '6'}
    - {allow_navigation: false, floor_name: '7'}
    - {allow_navigation: true, floor_name: '8'}
    - {allow_navigation: true, floor_name: '9'}
    - {allow_navigation: true, floor_name: '10'}
    - {allow_navigation: true, floor_name: '11'}
    - {allow_navigation: true, floor_name: '12'}
    - {allow_navigation: true, floor_name: '13'}
```

</p>
</details>

## Expected results

* [ ] You could generate the model properly.
* [ ] The floor is detected correctly.
* [ ] The robot CANNOT navigate on the 7th floor.
* [ ] Sensor monitor shows the floor check failing.

<details><summary>Sensor monitor check</summary>
<p>

Run:
```shell
$ rostopic echo -n 1 sensor_statuses
```
And check that the output matches this extract:

```yaml
checks:
[...]
  -
    topic: barometric_floor_new
    frame_id: barometer
    check_id: floor_check
    check_successful: False
[...]
is_failing: True
```

</p>
</details>

## Post testing steps

* [ ] Edit the building model in `savioke-config` to enable navigation on the 7th floor.
